"""
build_installer.py — Build the Drawing Viewer Windows installer.

Steps:
  1. Read credentials from config.py
  2. Encrypt them into credentials.bin using a persistent Fernet key
  3. Write _runtime_config.py (embedded key + decrypt logic; compiled into the exe)
  4. Run PyInstaller  →  dist/DrawingViewer/
  5. Run Inno Setup  →  installer_output/DrawingViewerSetup.exe

Run this on YOUR dev machine (where config.py lives).
Prerequisites:
  pip install pyinstaller cryptography
  Inno Setup installed (https://jrsoftware.org/isinfo.php)
"""

import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent

# All config keys to bundle.  Keys absent from config.py are silently skipped.
CREDENTIAL_KEYS = [
    "EPICOR_BASE_URL", "EPICOR_COMPANY", "EPICOR_PLANT",
    "EPICOR_API_KEY", "EPICOR_USERNAME", "EPICOR_PASSWORD",
    "BOX_CLIENT_ID", "BOX_CLIENT_SECRET", "BOX_ENTERPRISE_ID",
    "BOX_DRAWINGS_FOLDER_ID",
    "DATABASE_URL",
    "MONDAY_API_TOKEN", "MONDAY_BOARD_ID", "MONDAY_PARTS_BOARD_ID",
]

# Inno Setup compiler — tried in order until one is found
ISCC_CANDIDATES = [
    "ISCC",
    r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    r"C:\Program Files\Inno Setup 6\ISCC.exe",
    r"C:\Program Files (x86)\Inno Setup 5\ISCC.exe",
]


def find_iscc() -> str | None:
    for candidate in ISCC_CANDIDATES:
        try:
            subprocess.run([candidate, "/?"], capture_output=True)
            return candidate
        except FileNotFoundError:
            continue
    return None


def main() -> None:
    # ── 1. Load credentials ─────────────────────────────────────────────
    print("Loading credentials from config.py...")
    try:
        import config as cfg
    except ImportError:
        print("ERROR: config.py not found.")
        print("       Copy config.example.py → config.py and fill in your credentials.")
        sys.exit(1)

    creds: dict = {}
    for key in CREDENTIAL_KEYS:
        val = getattr(cfg, key, None)
        if val is not None:
            creds[key] = val

    if not creds:
        print("ERROR: No credentials found in config.py.")
        sys.exit(1)
    print(f"  Bundling {len(creds)} credential keys: {', '.join(creds)}")

    # ── 2. Load or create persistent Fernet key ─────────────────────────
    #
    # The key is persisted so you can re-build without invalidating a
    # credentials.bin you've already deployed separately.
    #
    from cryptography.fernet import Fernet

    key_file = HERE / "_fernet_key.bin"
    if key_file.exists():
        key = key_file.read_bytes()
        print("  Using existing Fernet key from _fernet_key.bin.")
    else:
        key = Fernet.generate_key()
        key_file.write_bytes(key)
        print("  Generated new Fernet key → _fernet_key.bin  (keep this safe, never commit it).")

    # ── 3. Encrypt credentials ──────────────────────────────────────────
    encrypted = Fernet(key).encrypt(json.dumps(creds).encode())
    creds_bin = HERE / "credentials.bin"
    creds_bin.write_bytes(encrypted)
    print(f"  Encrypted credentials → credentials.bin ({len(encrypted)} bytes).")

    # ── 4. Write _runtime_config.py ─────────────────────────────────────
    #
    # This module is compiled into the exe by PyInstaller.  It decrypts
    # credentials.bin at startup and exposes the same names as config.py.
    #
    runtime_src = (
        "# AUTO-GENERATED by build_installer.py — do not edit or commit\n"
        "import json, os, sys\n"
        "from cryptography.fernet import Fernet\n"
        "\n"
        f"_KEY = {key!r}\n"
        "\n"
        "def _load() -> None:\n"
        '    base = sys._MEIPASS if getattr(sys, "frozen", False) else os.path.dirname(os.path.abspath(__file__))\n'
        '    path = os.path.join(base, "credentials.bin")\n'
        "    data = json.loads(Fernet(_KEY).decrypt(open(path, 'rb').read()))\n"
        "    globals().update(data)\n"
        "\n"
        "_load()\n"
    )
    runtime_path = HERE / "_runtime_config.py"
    runtime_path.write_text(runtime_src, encoding="utf-8")
    print("  Wrote _runtime_config.py.")

    # ── 5. PyInstaller ──────────────────────────────────────────────────
    print("\nRunning PyInstaller...")
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--clean", "drawing_viewer.spec"],
        cwd=HERE,
    )
    if result.returncode != 0:
        print("\nERROR: PyInstaller failed (see output above).")
        sys.exit(1)
    print("PyInstaller complete.")

    # ── 6. Inno Setup ───────────────────────────────────────────────────
    print("\nRunning Inno Setup...")
    iscc = find_iscc()
    if iscc is None:
        print("WARNING: ISCC not found — skipping installer creation.")
        print("         Install Inno Setup, then run manually:")
        print(f'           ISCC "{HERE / "DrawingViewer.iss"}"')
        print(f"\nPyInstaller output is in:  {HERE / 'dist' / 'DrawingViewer'}")
    else:
        result = subprocess.run([iscc, str(HERE / "DrawingViewer.iss")], cwd=HERE)
        if result.returncode != 0:
            print("\nERROR: Inno Setup failed (see output above).")
            sys.exit(1)
        installer = HERE / "installer_output" / "DrawingViewerSetup.exe"
        print(f"\nInstaller ready:  {installer}")


if __name__ == "__main__":
    main()
