# drawing_viewer.spec — PyInstaller spec for Drawing Viewer
# Generated/maintained manually.  Run via build_installer.py.
# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["drawing_viewer.py"],
    pathex=[],
    binaries=[],
    datas=[
        # Bundle the encrypted credentials alongside the exe
        ("credentials.bin", "."),
    ],
    hiddenimports=[
        # Credential loader (generated by build_installer.py)
        "_runtime_config",
        # SQLAlchemy dialects
        "sqlalchemy.dialects.sqlite",
        "sqlalchemy.dialects.postgresql",
        "sqlalchemy.dialects.postgresql.psycopg2",
        "psycopg2",
        # Box SDK internals that PyInstaller may miss
        "box_sdk_gen",
        "httpx",
        "httpcore",
        # Pillow tkinter bridge
        "PIL._tkinter_finder",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=["runtime_hook_config.py"],
    # Never bundle the dev config.py — credentials come from credentials.bin
    excludes=["config"],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="DrawingViewer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,          # GUI only — no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="DrawingViewer",
)
